import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{color: '#BDC6CC', background: '#24243E', height: '100%'}} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
